Creating a new dimension Region Name
FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec pull request #353
Opened 2024-03-04 22:10 UTC by SanjnaSrivatsaVMware

@ljadvey to add more details in the supporting documents. I am pushing a  skeleton of that currently.

2024-03-05 01:39 UTC, udam-f2 commented on supporting_content/columns/regionname.md
> +## Example provider mappings
Lets not copy / paste the RegionId here. Instead in other places we've linked to that other field using a ../regionid.md type notation. Feel free to capture anything new here though.

2024-03-05 01:41 UTC, udam-f2 commented
> @ljadvey to add more details in the supporting documents. I am pushing a skeleton of that currently.

Added WIP to PR since this is not yet ready per the comment above.

2024-03-07 20:43 UTC, jpradocueva commented
This PR has been moved to `5 days Review and Approval`. It needs the approval of at least three members and two maintainers to be considered as approved by the group.
@SanjnaSrivatsaVMware, @udam-f2, @ljadvey, could you please review the PR and approve it or provide your comments? Thanks

2024-03-07 20:59 UTC, cnharris10 requested changes

2024-03-07 20:59 UTC, cnharris10 commented on specification/columns/regionname.md
> +Region Name MUST be present in the billing data and MUST be of type String. Region Name MUST NOT be null when a *resource* or *service* is operated in or managed from a distinct region by the Provide
Similar as in https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/352, we need to say something like:

```
The Region Name column MUST be present in the billing data when the provider supports deploying resources or services within an *region*.
```

Udam has a few examples here: https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/352

2024-03-07 20:59 UTC, cnharris10 commented on specification/columns/regionname.md
> +| Column required | True            |
```suggestion
| FOCUS Essential | False            |
```

2024-03-08 16:36 UTC, jpradocueva commented
@ljadvey do you have any comments on the latest proposal by Chris Harris?

2024-03-12 18:47 UTC, udam-f2 commented on supporting_content/columns/regionname.md
> +| OCI       | Cost reports             |  |
can we get these filled out?

2024-03-12 18:47 UTC, udam-f2 commented on supporting_content/columns/regionname.md
> +  - OCI: [https://docs.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm](https://docs.oracle.com/en-us/iaas/Content/General/Concepts/regions.htm)
Rather than duplicating, let's reference the discussion in regionid.md

2024-03-12 18:47 UTC, udam-f2 commented on specification/columns/region.md
> +# Region ID
Let's rebase from working_draft or resolve conflicts here.

2024-03-13 23:44 UTC, cnharris10 approved these changes

2024-03-14 00:06 UTC, mike-finopsorg approved these changes
I like this addition to the spec for the reason that CSPs sometimes use their name vs Id in API responses and the like. So connecting data to the cloud bill can be challenging or require the practitioner to map Id to Name in order to associate data.

2024-03-15 15:12 UTC, aqu-erp commented on specification/columns/regionname.md
> +RegionName MUST be present in the billing data when the provider supports deploying resources or services within an *region* and MUST be of type String. RegionName MUST NOT be null when a *resource*
What if a service is restricted to multiple regions? Example: multi-regional GCP resources where the data is replicated across regions defined in the instance configuration.

2024-03-19 02:03 UTC, jpradocueva commented
This PR will be put forward for approval on Thursday, March 21.

2024-03-21 18:27 UTC, flanakin approved these changes

2024-03-21 18:27 UTC, flanakin commented on specification/columns/.Rhistory
Is this supposed to be here?

2024-03-21 18:27 UTC, flanakin commented on specification/columns/regionname.md
> +RegionName MUST be present in the billing data when the provider supports deploying resources or services within an *region* and MUST be of type String. RegionName MUST NOT be null when a *resource*
```suggestion
RegionName MUST be present in the billing data when the provider supports deploying resources or services within an *region* and MUST be of type String. RegionName MUST NOT be null when a *resource* or *service* is operated in or managed from a distinct region by the Provider and MAY contain null values when a *resource* or *service* is not restricted to an isolated geographic area. RegionName MUST be consistent within the provider and MUST be the same value used to indicate the region when provisioning or purchasing the *resource* or *service*.
```

2024-03-21 18:27 UTC, flanakin commented on specification/columns/regionname.md
> +Region Name is a provider-assigned name for an isolated geographic area where a [*resource*](#glossary:resource) is provisioned or a [*service*](#glossary:service) is provided. Region Name is commonl
```suggestion
Region Name is a provider-assigned display name for an isolated geographic area where a [*resource*](#glossary:resource) is provisioned or a [*service*](#glossary:service) is provided. Region Name is commonly used for scenarios like analyzing cost and unit prices based on where *resources* are deployed.
```

2024-03-21 18:53 UTC, tobrien approved these changes

2024-03-21 22:41 UTC, udam-f2 commented on specification/columns/.Rhistory
the git graph for this is a wreck. Not sure where it came from but now fixed.

2024-03-21 22:41 UTC, merged