18 account name dimension
FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec pull request #96
Opened 2023-05-30 18:51 UTC by MichaelArkoosh-vega

2023-05-31 21:16 UTC, rileyjenk requested changes
Sub Accounts can generate invoices.

2023-06-01 21:39 UTC, MichaelArkoosh-vega commented
> Sub Accounts can generate invoices.

Where they can generate and invoice (meaning usage in the account can result in an invoice (example I purchase an RI in sub account A.) I think we may need to change the terminology to "Sub accounts must be associated with a billing account as they do not **receive** invoices." - Thoughts?

2023-06-02 20:06 UTC, MichaelArkoosh-vega commented
> @udam-f2 They do roll up to the billing account - but that is why I was wondering if we wanted to move from generate to receive? As the underlying usage the invoice is generated from is in the the sub account but the invoice is received at the billing account.

2023-06-02 20:32 UTC, udam-f2 commented
> > @udam-f2 They do roll up to the billing account - but that is why I was wondering if we wanted to move from generate to receive? As the underlying usage the invoice is generated from is in the the sub account but the invoice is received at the billing account.

Ah, got it now.. then yes, that makes sense. The only odd case we may need to verify is MSP type cases? Seems like they would be fine as well since the invoice is received by the MSP from the billing account. They may generate a different invoice for their underlying customers.

2023-06-06 16:25 UTC, MichaelArkoosh-vega commented
Updated the verbiage in the spec document to state "Sub Accounts do not receive an invoice" as, even though the invoice may show in the sub account it is the billing account that will receive/pay said invoice.

2023-06-06 17:33 UTC, flanakin commented on specification/dimensions/subaccountname.md
> +The SubAccountName column MUST be present in the billing data. This column MUST be of type String and MUST NOT contain null values. Where a provider doesn't support a sub account construct (only has
Does this convey what we discussed?
```suggestion
The SubAccountName column MUST be present in the billing data. This column MUST be of type String and SHOULD NOT contain null values. If a provider doesn't support a sub account construct (only has a billing account), use the BillingAccountName value. If a provider does support a sub account construct, but the charge does not apply to a sub account, the SubAccountName column may be null.
```

2023-06-08 16:03 UTC, ijurica commented on specification/dimensions/subaccountname.md
> +
a few notes:

- selected block should be removed
- Sub Account Name should be Heading L1 and all others Heading L2

2023-06-08 16:48 UTC, rileyjenk commented on supporting_content/dimensions/subaccountname.md
> +#### Example provider mappings
After pulling some examples and looking various options for account structures in AWS here is what was found. 
1.) There are multiple ways to have multiple invoice generating accounts in AWS regardless if the are stand-alone, master-payer, or linked accounts.  This means that from an AWS side an account can be a sub account (linked account) to a higher order account (master payer account) and generate its own invoice and will not be included on the master payer.

That being said as far as FOCUS is concerned , any account that generates an invoice is considered a billing account. The provider may also specify it as a sub account. In the data there won't be a link in the data for true relationship.

2023-06-08 17:23 UTC, merged